# Generated by Django 5.0.6 on 2024-06-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='name_ja',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
