# Generated by Django 5.0.6 on 2024-06-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonapp', '0002_rename_name_pokemon_name_en_pokemon_name_ja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='species',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
