# Generated by Django 5.0.6 on 2024-06-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonapp', '0003_pokemon_species_pokemon_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='species',
            new_name='genus',
        ),
    ]
