# Generated by Django 5.0.6 on 2024-06-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonapp', '0004_rename_species_pokemon_genus'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
