# Generated by Django 5.0.6 on 2024-06-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonapp', '0005_pokemon_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='ability',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='text',
            field=models.TextField(default=None),
        ),
    ]
